language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: bMuhY3/qV5zUQf2WOcK9yL4CxpowTvJ95UXULo8YtagBw+yE4UBbMPuWrHVMP9qTGVrJf/DVsfvxgidEOaZnFdjrm93/NpVo8ugUErqc/Zx09cgRzPVVQk9q/5n/mP2HnOQaS9tlvrjNce4dlcz0gouAGB9prR2tBzvfYDEc3CjuvOWxA/fNI+L+9aYcXqaIFyAcITLB7QN5OVuRp7kWMa+mdHkuA29NiHFRccJph0fjaR6AA5j8ZrzO6y0oyPRt19oImfqQMuqKzaI2v71zL+R8x+/ffXrug/HKQjg1P+JfKkxcu0ac13ov4AYJz9Fasl+vlQm+YpOCBiPXxApvxxWKpSoelRo0Zo/d0xuuyFjC0SbGVRqyiOMLUGL/XUob0owlUBVwPODlbeE41unmy0kp1lEB8JQnc83x1HOnJpmGed875gpX5x3BqE26WRkiguVpb0gw9EtaS6a6/AeQ2OIPuaQ/tnmamSNhQZBkjpQK/in7XBttm/P8+2e8vEbXjg+adQC/v+NelVoTneejOpbqSfYnWQ73kf0lWWvl51vKJCIsrR9zU7FjyvAB3B7az9R36K+aZHr8fsGO4zZrignfbaEB/UKpwi1eIaDGku5iYzgKGpn9SmAp9SgYwxrCMewkWPyKbnjUaxNcGymMLqsC2N5omPWwpKUijnL98X4=
  app: dry-waters-53761
  on:
    repo: matteprg/book-shelf-api
