language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: 63d3bf86-c743-4e25-b00b-7ac614dffe36
  app: dry-waters-53761
  on:
    repo: matteprg/book-shelf-api
